auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:categories/:year:month:day/:title.html

title:            Yonzeo
url:              http://www.zhengyangyang.cn
feed:             /atom.xml
author:
    name:         Yonzeo
description:      "Yonzeo\'s Blog"
author_info:      <a href="http://www.zhengyangyang.cn/about.html">Yonzeo</a>

copyright:
    - Design by <a href="http://www.zhengyangyang.cn/about.html" title="Yonzeo" target="_blank">Yonzeo</a> &copy; Copyright 2012
