---
layout:           default
---
<plist version="1.0">
<dict>
    <key>items</key>
    <array>
        <dict>
            <key>assets</key>
            <array>
                <dict>
                    <key>kind</key>
                    <string>software-package</string>
                    <key>url</key>
                    <string>http://userios.xmniao.com/XMNiao_CustomerTest.ipa</string>
                </dict>
                <dict>
                    <key>kind</key>
                    <string>display-image</string>
                    <key>needs-shine</key>
                    <true/>
                    <key>url</key>
                    <string>http://222.qiniudn.com/icon@2x.png</string>
                </dict>
                <dict>
                    <key>kind</key>
                    <string>full-size-image</string>
                    <key>needs-shine</key>
                    <true/>
                    <key>url</key>
                    <string>http://222.qiniudn.com/icon@2x.png</string>
                </dict>
            </array>
            <key>metadata</key>
            <dict>
                <key>bundle-identifier</key>
                <string>com.XMNiao.Customer.XMNiao-Customer</string>
                <key>bundle-version</key>
                <string>1.0.2</string>
                <key>kind</key>
                <string>software</string>
                <key>subtitle</key>
                <string>爱如潮水</string>
                <key>title</key>
                <string>XMNIAO App download</string>
            </dict>
        </dict>
    </array>
</dict>
</plist>
